version: '3.4'

services:
  twooter.userservice:
    image: ${DOCKER_REGISTRY-}twooter
    build:
      context: .
      dockerfile: Twooter.UserService/Dockerfile
    depends_on:
      - db
  twooter.urlgenerationservice:
    image: ${DOCKER_REGISTRY-}twooter
    build:
      context: .
      dockerfile: Twooter.UrlGenerationService/Dockerfile
    depends_on:
      - db
  twooter.twootrealtimeservice:
    image: ${DOCKER_REGISTRY-}twooter
    build:
      context: .
      dockerfile: Twooter.TwootRealtimeService/Dockerfile
    depends_on:
      - db
  twooter.twootreactionservice:
    image: ${DOCKER_REGISTRY-}twooter
    build:
      context: .
      dockerfile: Twooter.TwootReactionService/Dockerfile
    depends_on:
      - db
  twooter.twootcontentservice:
    image: ${DOCKER_REGISTRY-}twooter
    build:
      context: .
      dockerfile: Twooter.TwootContentService/Dockerfile
    depends_on:
      - db
  twooter.twootcommentservice:
    image: ${DOCKER_REGISTRY-}twooter
    build:
      context: .
      dockerfile: Twooter.TwootCommentService/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
